- hosts: tag_Name_ansible_wn
  become: true
  tasks:
    - name: copy war file from jenkins to tomcat
      copy:
        src: webapp/target/webapp.war
        dest: /opt/tomcat/webapps/
        deploy adapters: [tomcat8(path: '/opt/tomcat/webapps/target', url: '')], contextPath: null, war: '**/*.war'
